### ISSUE TITLE
An execution issue 

### ISSUE THREAD

**Issue by Monia234** [pgxcentre/region-plot#3]
Hi 
Please could you help with this error : 
Traceback (most recent call last):
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\indexes\base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'minor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\Scripts\launch-region-plot-script.py", line 11, in <module>
    load_entry_point('region-plot==0.1.3', 'console_scripts', 'launch-region-plot')()
  File "c:\users\user\miniconda3\lib\site-packages\region_plot-0.1.3-py3.8.egg\region_plot\cli.py", line 66, in main
  File "c:\users\user\miniconda3\lib\site-packages\region_plot-0.1.3-py3.8.egg\region_plot\cli.py", line 440, in read_assoc
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\indexing.py", line 786, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\indexing.py", line 1110, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\indexing.py", line 1059, in _get_label
    return self.obj.xs(label, axis=axis)
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\generic.py", line 3485, in xs
    return self[key]
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\indexes\base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'minor'

I got the same error with UBUNTU 

Thanks

**Comment by lemieuxl** [comment]
The error appears because the tool expects the two allele columns to be `minor` and `major` in the summary statistics. You can use the two following options to change the behaviour: `--a1-col` (which defaults to `minor`) and `--a2-col` (which defaults to `major`).

You can use the following command to know more about the tool's options.

```bash
launch-region-plot --help
```

**Comment by Monia234** [comment]
Thank you very much, I noticed that the help menu is diffrent from this in the readme file ...
Now I have this error message : 


`    load_entry_point('region-plot==0.1.3', 'console_scripts', 'launch-region-plot')()
  File "c:\users\user\miniconda3\lib\site-packages\region_plot-0.1.3-py3.8.egg\region_plot\cli.py", line 69, in main
  File "c:\users\user\miniconda3\lib\site-packages\region_plot-0.1.3-py3.8.egg\region_plot\cli.py", line 464, in get_best_hits
  File "c:\users\user\miniconda3\lib\site-packages\pandas-1.1.3-py3.8-win-amd64.egg\pandas\core\generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pos'`


I am usin,g the output file of plink with A2 column added, pos=BP  this is my code : 

`launch-region-plot --log-file chr6.log  --assoc assoc.chr6.region_plot.txt --imputed-sites imputed_chr6.txt --snp-col SNP --chr-col CHR --pos-col BP --p-col P --genetic-map genetic_map_GRCh38_merged.tab  --genetic-chr-col chrom --genetic-pos-col pos --genetic-rate-col recomb_rate  --plot-format png --build  GRCh38 --whole-dataset --genotypes chr6.2ref.signal.gen --a2-col A2 --a1-col A1 --genotypes-format impute2`

Could you help please ? 

Thanks

**Comment by lemieuxl** [comment]
Could you try the *dev* branch to test the fix?
I forgot to change the hard-coded column name for position at this place...

I'll try and update the README at the same time.

**Comment by Monia234** [comment]
Thank you very much, the dev branch is working well  !
